In [10]:
from autogluon.tabular import TabularDataset, TabularPredictor
import pandas as pd

In [11]:
df = pd.read_csv("data/datas_cleaned.csv")
df.head()

   year   region size_estabish        value  size_rank
0  2542  Bangkok           <60  297061700.0          1
1  2544  Bangkok           <60  316149600.0          1
2  2546  Bangkok           <60  292475000.0          1
3  2548  Bangkok           <60  318711400.0          1
4  2550  Bangkok           <60  443951100.0          1

In [12]:
train_data = TabularDataset(df[df["year"] <= 2554].drop(columns=["size_estabish"]))
test_data = TabularDataset(df[df["year"] >= 2556].drop(columns=["size_estabish"]))

In [13]:
train_data["value"].describe()

count    1.050000e+02
mean     5.046461e+09
std      7.965187e+09
min      2.223934e+08
25%      8.673075e+08
50%      1.726217e+09
75%      5.033558e+09
max      3.997165e+10
Name: value, dtype: float64

In [14]:
predictor = TabularPredictor(label="value", problem_type="regression").fit(
    train_data,
    presets="medium_quality",
)

No path specified. Models will be saved in: "AutogluonModels\ag-20260307_094817"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.12.10
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          20
Pytorch Version:    2.9.1+cpu
CUDA Version:       CUDA is not available
Memory Avail:       2.31 GB / 15.73 GB (14.7%)
Disk Space Avail:   637.02 GB / 953.85 GB (66.8%)
===================================================
Presets specified: ['medium_quality']
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ...
AutoGluon will save models to "d:\Mini Project\Term Project\AutogluonModels\ag-20260307_094817"
Train Data Rows:    105
Train Data Columns: 3
Label Column:       value
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    2336.85 MB
	Train Data (Original)  Memory Usage: 0.01 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', [])    : 2 | ['year', 'size_rank']
		('object', []) : 1 | ['region']
	Types of features in processed data (raw dtype, special dtypes):
		('category', []) : 1 | ['region']
		('int', [])      : 2 | ['year', 'size_rank']
	0.0s = Fit runtime
	3 features in original data used to generate 3 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.03s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 84, Val Rows: 21
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 9 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT ...
	Fitting with cpus=14, gpus=0, mem=0.0/2.3 GB
	-6717252163.9083	 = Validation score   (-root_mean_squared_error)
	0.27s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM ...
	Fitting with cpus=14, gpus=0, mem=0.0/2.3 GB
	-6105197116.132	 = Validation score   (-root_mean_squared_error)
	0.27s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestMSE ...
	Fitting with cpus=20, gpus=0
	-2079616461.6207	 = Validation score   (-root_mean_squared_error)
	0.41s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: CatBoost ...
	Fitting with cpus=14, gpus=0
	-3556949680.4439	 = Validation score   (-root_mean_squared_error)
	121.59s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesMSE ...
	Fitting with cpus=20, gpus=0
	-2280311309.056	 = Validation score   (-root_mean_squared_error)
	0.33s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	Fitting with cpus=14, gpus=0, mem=0.0/4.3 GB
	-3961374660.9133	 = Validation score   (-root_mean_squared_error)
	0.53s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: XGBoost ...
	Fitting with cpus=14, gpus=0
	-4340817694.9239	 = Validation score   (-root_mean_squared_error)
	0.21s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	Fitting with cpus=14, gpus=0, mem=0.0/4.3 GB
d:\Mini Project\Term Project\.venv\Lib\site-packages\sklearn\compose\_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(
	-1344293960.0818	 = Validation score   (-root_mean_squared_error)
	2.19s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMLarge ...
	Fitting with cpus=14, gpus=0, mem=0.1/4.3 GB
	-7018678421.9186	 = Validation score   (-root_mean_squared_error)
	0.29s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Fitting 1 model on all data | Fitting with cpus=20, gpus=0, mem=0.0/4.3 GB
	Ensemble Weights: {'NeuralNetTorch': 0.85, 'ExtraTreesMSE': 0.15}
	-1303406456.1232	 = Validation score   (-root_mean_squared_error)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 126.45s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 655.0 rows/s (21 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("d:\Mini Project\Term Project\AutogluonModels\ag-20260307_094817")

In [15]:
predictor.evaluate(test_data)

{'root_mean_squared_error': np.float64(-8651249234.962206),
 'mean_squared_error': -7.484411332543416e+19,
 'mean_absolute_error': -6711910199.6,
 'r2': 0.5017377482572795,
 'pearsonr': 0.745256252221621,
 'median_absolute_error': -5988100162.0}

In [16]:
predictor.leaderboard(test_data)

,model,score_test,score_val,eval_metric,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,RandomForestMSE,-7.544564e+09,-2.079616e+09,root_mean_squared_error,0.074575,0.029298,0.406177,0.074575,0.029298,0.406177,1,True,3
1,ExtraTreesMSE,-7.653866e+09,-2.280311e+09,root_mean_squared_error,0.045492,0.029060,0.325479,0.045492,0.029060,0.325479,1,True,5
2,CatBoost,-8.616218e+09,-3.556950e+09,root_mean_squared_error,0.024975,0.002004,121.588840,0.024975,0.002004,121.588840,1,True,4
3,WeightedEnsemble_L2,-8.651249e+09,-1.303406e+09,root_mean_squared_error,0.053491,0.032060,2.518215,0.001999,0.000000,0.006000,2,True,10
4,NeuralNetTorch,-9.071982e+09,-1.344294e+09,root_mean_squared_error,0.006000,0.003000,2.186737,0.006000,0.003000,2.186737,1,True,8
5,XGBoost,-9.295586e+09,-4.340818e+09,root_mean_squared_error,0.037230,0.007998,0.205471,0.037230,0.007998,0.205471,1,True,7
6,NeuralNetFastAI,-9.722600e+09,-3.961375e+09,root_mean_squared_error,0.034862,0.004000,0.525158,0.034862,0.004000,0.525158,1,True,6
7,LightGBM,-1.205696e+10,-6.105197e+09,root_mean_squared_error,0.020000,0.010003,0.269211,0.020000,0.010003,0.269211,1,True,2
8,LightGBMXT,-1.246348e+10,-6.717252e+09,root_mean_squared_error,0.020998,0.008002,0.268755,0.020998,0.008002,0.268755,1,True,1
9,LightGBMLarge,-1.270403e+10,-7.018678e+09,root_mean_squared_error,0.020004,0.008001,0.291805,0.020004,0.008001,0.291805,1,True,9

In [17]:
predictor.predict(test_data, model="RandomForestMSE")

7      4.805047e+09
8      4.805047e+09
16     4.795042e+09
17     4.795042e+09
25     2.604608e+10
26     2.604608e+10
34     9.239027e+09
35     9.239027e+09
43     7.933599e+09
44     7.933599e+09
52     1.318120e+10
53     1.318120e+10
61     4.732695e+09
62     4.732695e+09
70     4.383633e+09
71     4.383633e+09
79     5.734671e+09
80     5.734671e+09
88     4.098944e+09
89     4.098944e+09
97     3.617869e+09
98     3.617869e+09
106    4.956109e+09
107    4.956109e+09
115    1.906686e+10
116    1.906686e+10
124    1.830072e+10
125    1.830072e+10
133    1.888939e+10
134    1.888939e+10
Name: value, dtype: float32