In [1]:
from autogluon.tabular import TabularDataset, TabularPredictor

In [3]:
data_url = "https://raw.githubusercontent.com/mli/ag-docs/main/knot_theory/"
train_data = TabularDataset(f"{data_url}train.csv")
train_data.head()

,Unnamed: 0,chern_simons,cusp_volume,hyperbolic_adjoint_torsion_degree,hyperbolic_torsion_degree,injectivity_radius,longitudinal_translation,meridinal_translation_imag,meridinal_translation_real,short_geodesic_imag_part,short_geodesic_real_part,Symmetry_0,Symmetry_D3,Symmetry_D4,Symmetry_D6,Symmetry_D8,Symmetry_Z/2 + Z/2,volume,signature
0,70746,0.090530,12.226322,0,10,0.507756,10.685555,1.144192,-0.519157,-2.760601,1.015512,0.0,0.0,0.0,0.0,0.0,1.0,11.393225,-2
1,240827,0.232453,13.800773,0,14,0.413645,10.453156,1.320249,-0.158522,-3.013258,0.827289,0.0,0.0,0.0,0.0,0.0,1.0,12.742782,0
2,155659,-0.144099,14.761030,0,14,0.436928,13.405199,1.101142,0.768894,2.233106,0.873856,0.0,0.0,0.0,0.0,0.0,0.0,15.236505,2
3,239963,-0.171668,13.738019,0,22,0.249481,27.819496,0.493827,-1.188718,-2.042771,0.498961,0.0,0.0,0.0,0.0,0.0,0.0,17.279890,-8
4,90504,0.235188,15.896359,0,10,0.389329,15.330971,1.036879,0.722828,-3.056138,0.778658,0.0,0.0,0.0,0.0,0.0,0.0,16.749298,4

In [4]:
label = "signature"
train_data[label].describe()

count    10000.000000
mean        -0.022000
std          3.025166
min        -12.000000
25%         -2.000000
50%          0.000000
75%          2.000000
max         12.000000
Name: signature, dtype: float64

In [5]:
predictor = TabularPredictor(label=label).fit(train_data, num_gpus=1)

No path specified. Models will be saved in: "AutogluonModels\ag-20260307_045314"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.4
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          20
Pytorch Version:    2.9.1+cu128
CUDA Version:       12.8
GPU Memory:         GPU 0: 7.96/7.96 GB
Total GPU Memory:   Free: 7.96 GB, Allocated: 0.00 GB, Total: 7.96 GB
GPU Count:          1
Memory Avail:       4.61 GB / 15.73 GB (29.3%)
Disk Space Avail:   639.39 GB / 953.85 GB (67.0%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme'  : New in v1.5: The state-of-the-art for tabular data. Massively better than 'best' on datasets <100000 samples by using new Tabular Foundation Models (TFMs) meta-learned on https://tabarena.ai: TabPFNv2, TabICL, Mitra, TabDPT, and TabM. Requires a GPU and `pip install autogluon.tabular[tabarena]` to install TabPFN, TabICL, and TabDPT.
	presets='best'     : Maximize accuracy. Recommended for most users. Use in competitions and benchmarks.
	presets='best_v150': New in v1.5: Better quality than 'best' and 5x+ faster to train. Give it a try!
	presets='high'     : Strong accuracy with fast inference speed.
	presets='high_v150': New in v1.5: Better quality than 'high' and 5x+ faster to train. Give it a try!
	presets='good'     : Good accuracy with very fast inference speed.
	presets='medium'   : Fast training time, ideal for initial prototyping.
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ...
AutoGluon will save models to "d:\Mini Project\Term Project\AutogluonModels\ag-20260307_045314"
Train Data Rows:    10000
Train Data Columns: 18
Label Column:       signature
AutoGluon infers your prediction problem is: 'multiclass' (because dtype of label-column == int, but few unique label-values observed).
	First 10 (of 13) unique label values:  [np.int64(-2), np.int64(0), np.int64(2), np.int64(-8), np.int64(4), np.int64(-4), np.int64(-6), np.int64(8), np.int64(6), np.int64(10)]
	If 'multiclass' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       multiclass
Preprocessing data ...
Warning: Some classes in the training set have fewer than 10 examples. AutoGluon will only keep 9 out of 13 classes for training and will not try to predict the rare classes. To keep more classes, increase the number of datapoints from these rare classes in the training data or reduce label_count_threshold.
Fraction of data from classes with at least 10 examples that will be kept for training models: 0.9984
Train Data Class Count: 9
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    4704.87 MB
	Train Data (Original)  Memory Usage: 1.37 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 5 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Useless Original Features (Count: 1): ['Symmetry_D8']
		These features carry no predictive signal and should be manually investigated.
		This is typically a feature which has the same value for all rows.
		These features do not need to be present at inference time.
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 14 | ['chern_simons', 'cusp_volume', 'injectivity_radius', 'longitudinal_translation', 'meridinal_translation_imag', ...]
		('int', [])   :  3 | ['Unnamed: 0', 'hyperbolic_adjoint_torsion_degree', 'hyperbolic_torsion_degree']
	Types of features in processed data (raw dtype, special dtypes):
		('float', [])     : 9 | ['chern_simons', 'cusp_volume', 'injectivity_radius', 'longitudinal_translation', 'meridinal_translation_imag', ...]
		('int', [])       : 3 | ['Unnamed: 0', 'hyperbolic_adjoint_torsion_degree', 'hyperbolic_torsion_degree']
		('int', ['bool']) : 5 | ['Symmetry_0', 'Symmetry_D3', 'Symmetry_D4', 'Symmetry_D6', 'Symmetry_Z/2 + Z/2']
	0.1s = Fit runtime
	17 features in original data used to generate 17 features in processed data.
	Train Data (Processed) Memory Usage: 0.96 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.18s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1, Train Rows: 8985, Val Rows: 999
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 11 L1 models, fit_strategy="sequential" ...
Fitting model: NeuralNetFastAI ...
	Fitting with cpus=14, gpus=1, mem=0.0/4.6 GB
	0.9409	 = Validation score   (accuracy)
	10.83s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: LightGBMXT ...
	Fitting with cpus=14, gpus=1, mem=0.1/4.0 GB
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	0.9479	 = Validation score   (accuracy)
	26.41s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: LightGBM ...
	Fitting with cpus=14, gpus=1, mem=0.1/4.1 GB
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.

[1000]	valid_set's multi_error: 0.045045

	0.957	 = Validation score   (accuracy)
	37.91s	 = Training   runtime
	0.11s	 = Validation runtime
Fitting model: RandomForestGini ...
	Fitting with cpus=20, gpus=0, mem=0.4/4.1 GB
	0.9449	 = Validation score   (accuracy)
	1.66s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: RandomForestEntr ...
	Fitting with cpus=20, gpus=0, mem=0.4/4.0 GB
	0.9499	 = Validation score   (accuracy)
	1.63s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: CatBoost ...
	Fitting with cpus=14, gpus=1
	Training CatBoost with GPU, note that this may negatively impact model quality compared to CPU training.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	0.9269	 = Validation score   (accuracy)
	30.81s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ...
	Fitting with cpus=20, gpus=0, mem=0.4/4.1 GB
	0.9469	 = Validation score   (accuracy)
	1.09s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	Fitting with cpus=20, gpus=0, mem=0.4/4.0 GB
	0.9429	 = Validation score   (accuracy)
	1.14s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: XGBoost ...
	Fitting with cpus=14, gpus=1
	0.955	 = Validation score   (accuracy)
	71.19s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	Fitting with cpus=14, gpus=1, mem=0.0/4.2 GB
d:\Mini Project\Term Project\.venv\Lib\site-packages\sklearn\compose\_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(
	0.951	 = Validation score   (accuracy)
	230.53s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMLarge ...
	Fitting with cpus=14, gpus=1, mem=0.6/3.8 GB
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	0.9479	 = Validation score   (accuracy)
	62.53s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Fitting 1 model on all data | Fitting with cpus=20, gpus=1, mem=0.0/3.9 GB
	Ensemble Weights: {'RandomForestEntr': 0.571, 'NeuralNetFastAI': 0.143, 'LightGBM': 0.143, 'NeuralNetTorch': 0.143}
	0.963	 = Validation score   (accuracy)
	0.06s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 478.53s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 4334.5 rows/s (999 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("d:\Mini Project\Term Project\AutogluonModels\ag-20260307_045314")

In [6]:
test_data = TabularDataset(f"{data_url}test.csv")

y_pred = predictor.predict(test_data.drop(columns=[label]))
y_pred.head()

Loaded data from: https://raw.githubusercontent.com/mli/ag-docs/main/knot_theory/test.csv | Columns = 19 / 19 | Rows = 5000 -> 5000

0   -4
1    0
2    0
3    4
4    2
Name: signature, dtype: int64

In [7]:
predictor.evaluate(test_data)

{'accuracy': 0.9482,
 'balanced_accuracy': np.float64(0.7480940950689591),
 'mcc': 0.9365228540031822}

In [8]:
predictor.leaderboard(test_data)

,model,score_test,score_val,eval_metric,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,LightGBM,0.9494,0.956957,accuracy,0.298522,0.113144,37.906411,0.298522,0.113144,37.906411,1,True,3
1,WeightedEnsemble_L2,0.9482,0.962963,accuracy,0.511682,0.230477,280.951197,0.008000,0.001027,0.057005,2,True,12
2,LightGBMLarge,0.9430,0.947948,accuracy,0.253432,0.036000,62.534772,0.253432,0.036000,62.534772,1,True,11
3,XGBoost,0.9392,0.954955,accuracy,0.121214,0.033001,71.185963,0.121214,0.033001,71.185963,1,True,9
4,RandomForestEntr,0.9384,0.949950,accuracy,0.113622,0.091295,1.633961,0.113622,0.091295,1.633961,1,True,5
5,NeuralNetTorch,0.9360,0.950951,accuracy,0.031000,0.004993,230.527892,0.031000,0.004993,230.527892,1,True,10
6,ExtraTreesGini,0.9360,0.946947,accuracy,0.209907,0.076675,1.091614,0.209907,0.076675,1.091614,1,True,7
7,NeuralNetFastAI,0.9358,0.940941,accuracy,0.060539,0.020017,10.825928,0.060539,0.020017,10.825928,1,True,1
8,ExtraTreesEntr,0.9358,0.942943,accuracy,0.234363,0.081810,1.144281,0.234363,0.081810,1.144281,1,True,8
9,RandomForestGini,0.9352,0.944945,accuracy,0.193718,0.092049,1.664960,0.193718,0.092049,1.664960,1,True,4
10,LightGBMXT,0.9336,0.947948,accuracy,0.111000,0.019000,26.410219,0.111000,0.019000,26.410219,1,True,2
11,CatBoost,0.9098,0.926927,accuracy,0.031009,0.004001,30.813579,0.031009,0.004001,30.813579,1,True,6