In [1]:
from autogluon.tabular import TabularDataset, TabularPredictor
import pandas as pd

In [2]:
df = pd.read_csv("data/datas_cleaned.csv")
df.head()

   year   region size_estabish        value  size_rank
0  2542  Bangkok           <60  297061700.0          1
1  2544  Bangkok           <60  316149600.0          1
2  2546  Bangkok           <60  292475000.0          1
3  2548  Bangkok           <60  318711400.0          1
4  2550  Bangkok           <60  443951100.0          1

In [3]:
train_data = TabularDataset(df[df["year"] <= 2554])
test_data = TabularDataset(df[df["year"] >= 2556])

In [5]:
train_data["value"].describe()

count    1.050000e+02
mean     5.046461e+09
std      7.965187e+09
min      2.223934e+08
25%      8.673075e+08
50%      1.726217e+09
75%      5.033558e+09
max      3.997165e+10
Name: value, dtype: float64

In [7]:
predictor = TabularPredictor(label="value", problem_type="regression").fit(
    train_data,
    presets="medium_quality",
)

No path specified. Models will be saved in: "AutogluonModels\ag-20260307_093640"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.12.10
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          20
Pytorch Version:    2.9.1+cpu
CUDA Version:       CUDA is not available
Memory Avail:       2.86 GB / 15.73 GB (18.2%)
Disk Space Avail:   637.03 GB / 953.85 GB (66.8%)
===================================================
Presets specified: ['medium_quality']
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ...
AutoGluon will save models to "d:\Mini Project\Term Project\AutogluonModels\ag-20260307_093640"
Train Data Rows:    105
Train Data Columns: 4
Label Column:       value
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    2926.06 MB
	Train Data (Original)  Memory Usage: 0.01 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', [])    : 2 | ['year', 'size_rank']
		('object', []) : 2 | ['region', 'size_estabish']
	Types of features in processed data (raw dtype, special dtypes):
		('category', []) : 2 | ['region', 'size_estabish']
		('int', [])      : 2 | ['year', 'size_rank']
	0.0s = Fit runtime
	4 features in original data used to generate 4 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.06s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 84, Val Rows: 21
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 9 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT ...
	Fitting with cpus=14, gpus=0, mem=0.0/2.9 GB
	-6280181288.8403	 = Validation score   (-root_mean_squared_error)
	0.8s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM ...
	Fitting with cpus=14, gpus=0, mem=0.0/2.8 GB
	-6105197116.132	 = Validation score   (-root_mean_squared_error)
	0.33s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestMSE ...
	Fitting with cpus=20, gpus=0
	-2071754254.128	 = Validation score   (-root_mean_squared_error)
	0.49s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: CatBoost ...
	Fitting with cpus=14, gpus=0
	-3170489727.3515	 = Validation score   (-root_mean_squared_error)
	50.49s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesMSE ...
	Fitting with cpus=20, gpus=0
	-2258508834.9659	 = Validation score   (-root_mean_squared_error)
	0.38s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	Fitting with cpus=14, gpus=0, mem=0.0/3.7 GB
	-3382119175.0358	 = Validation score   (-root_mean_squared_error)
	1.49s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ...
	Fitting with cpus=14, gpus=0
	-4340817694.9239	 = Validation score   (-root_mean_squared_error)
	0.43s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	Fitting with cpus=14, gpus=0, mem=0.0/3.6 GB
d:\Mini Project\Term Project\.venv\Lib\site-packages\sklearn\compose\_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(
	-1246232683.7512	 = Validation score   (-root_mean_squared_error)
	5.04s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBMLarge ...
	Fitting with cpus=14, gpus=0, mem=0.1/3.5 GB
	-7018678421.9186	 = Validation score   (-root_mean_squared_error)
	0.38s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Fitting 1 model on all data | Fitting with cpus=20, gpus=0, mem=0.0/3.7 GB
	Ensemble Weights: {'NeuralNetTorch': 0.864, 'ExtraTreesMSE': 0.136}
	-1208531171.1858	 = Validation score   (-root_mean_squared_error)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 60.35s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 531.2 rows/s (21 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("d:\Mini Project\Term Project\AutogluonModels\ag-20260307_093640")

In [8]:
predictor.evaluate(test_data)

{'root_mean_squared_error': np.float64(-9367366854.714272),
 'mean_squared_error': -8.774756179079954e+19,
 'mean_absolute_error': -7733458275.6,
 'r2': 0.4158351835539811,
 'pearsonr': 0.7001526169520844,
 'median_absolute_error': -6747785972.0}

In [9]:
predictor.leaderboard(test_data)

,model,score_test,score_val,eval_metric,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,RandomForestMSE,-7.495982e+09,-2.071754e+09,root_mean_squared_error,0.060595,0.031043,0.485423,0.060595,0.031043,0.485423,1,True,3
1,ExtraTreesMSE,-7.709292e+09,-2.258509e+09,root_mean_squared_error,0.042135,0.031530,0.382015,0.042135,0.031530,0.382015,1,True,5
2,CatBoost,-7.906528e+09,-3.170490e+09,root_mean_squared_error,0.013005,0.002000,50.492709,0.013005,0.002000,50.492709,1,True,4
3,XGBoost,-9.295586e+09,-4.340818e+09,root_mean_squared_error,0.031509,0.009000,0.434013,0.031509,0.009000,0.434013,1,True,7
4,WeightedEnsemble_L2,-9.367367e+09,-1.208531e+09,root_mean_squared_error,0.051137,0.039530,5.425842,0.001000,0.001000,0.007000,2,True,10
5,NeuralNetTorch,-9.845849e+09,-1.246233e+09,root_mean_squared_error,0.008002,0.007000,5.036827,0.008002,0.007000,5.036827,1,True,8
6,NeuralNetFastAI,-1.002805e+10,-3.382119e+09,root_mean_squared_error,0.037696,0.010003,1.490180,0.037696,0.010003,1.490180,1,True,6
7,LightGBMXT,-1.183201e+10,-6.280181e+09,root_mean_squared_error,0.019997,0.008000,0.804849,0.019997,0.008000,0.804849,1,True,1
8,LightGBM,-1.205696e+10,-6.105197e+09,root_mean_squared_error,0.017000,0.008004,0.332114,0.017000,0.008004,0.332114,1,True,2
9,LightGBMLarge,-1.270403e+10,-7.018678e+09,root_mean_squared_error,0.017507,0.009001,0.384797,0.017507,0.009001,0.384797,1,True,9