In [33]:
from autogluon.timeseries import TimeSeriesDataFrame, TimeSeriesPredictor
import pandas as pd
import numpy as np

In [34]:
save_path = "../AutogluonModels/TimeSeriesPredictor"
df = pd.read_csv("../data/processed/datas_cleaned.csv")
df["item_id"] = df["region"] + "_" + df["size_rank"].astype(str)
df["timestamp"] = pd.to_datetime((df["year"] - 543).astype(str))
df.head()

   year   region       value  size_rank  tourists_mn    item_id  timestamp
0  2542  Bangkok 297,061,700          1      3374540  Bangkok_1 1999-01-01
1  2544  Bangkok 316,149,600          1      3950714  Bangkok_1 2001-01-01
2  2546  Bangkok 292,475,000          1      5131993  Bangkok_1 2003-01-01
3  2548  Bangkok 318,711,400          1      4998658  Bangkok_1 2005-01-01
4  2550  Bangkok 443,951,100          1      4556018  Bangkok_1 2007-01-01

In [35]:
ts_df = TimeSeriesDataFrame.from_data_frame(
    df[["item_id", "timestamp", "value", "tourists_mn"]],
    id_column="item_id",
    timestamp_column="timestamp",
)
ts_df.head()

                           value  tourists_mn
item_id   timestamp
Bangkok_1 1999-01-01 297,061,700      3374540
          2001-01-01 316,149,600      3950714
          2003-01-01 292,475,000      5131993
          2005-01-01 318,711,400      4998658
          2007-01-01 443,951,100      4556018

In [36]:
predictor = TimeSeriesPredictor(
    prediction_length=2,
    target="value",
    eval_metric="MASE",
    known_covariates_names=["tourists_mn"],
    path=save_path,
).fit(ts_df, presets="best_quality", time_limit=600)

Warning: path already exists! This predictor may overwrite an existing predictor! path="../AutogluonModels/TimeSeriesPredictor"
Beginning AutoGluon training... Time limit = 600s
AutoGluon will save models to 'd:\Mini Project\Term Project\AutogluonModels\TimeSeriesPredictor'
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.12.10
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          20
Pytorch Version:    2.9.1+cpu
CUDA Version:       CUDA is not available
GPU Memory:
Total GPU Memory:   Free: 0.00 GB, Allocated: 0.00 GB, Total: 0.00 GB
GPU Count:          0
Memory Avail:       2.59 GB / 15.73 GB (16.5%)
Disk Space Avail:   636.25 GB / 953.85 GB (66.7%)
===================================================
Setting presets to: best_quality

Fitting with arguments:
{'enable_ensemble': True,
 'eval_metric': MASE,
 'hyperparameters': 'default',
 'known_covariates_names': ['tourists_mn'],
 'num_val_windows': 'auto',
 'prediction_length': 2,
 'quantile_levels': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
 'random_seed': 123,
 'refit_every_n_windows': 'auto',
 'refit_full': False,
 'skip_model_selection': False,
 'target': 'value',
 'time_limit': 600,
 'verbosity': 2}

Inferred time series frequency: '2YS-JAN'
Provided train_data has 135 rows, 15 time series. Median time series length is 9 (min=9, max=9).
Automatically setting num_val_windows=(1,) based on dataset properties
Automatically setting refit_every_n_windows=1 based on num_val_windows

Provided data contains following columns:
	target: 'value'
	known_covariates:
		categorical:        []
		continuous (float): ['tourists_mn']

To learn how to fix incorrectly inferred types, please see documentation for TimeSeriesPredictor.fit

AutoGluon will gauge predictive performance using evaluation metric: 'MASE'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
===================================================

Starting training. Start time is 2026-03-10 14:07:07
Models that will be trained: ['SeasonalNaive', 'RecursiveTabular', 'DirectTabular', 'DynamicOptimizedTheta', 'Chronos2', 'Chronos2SmallFineTuned', 'AutoETS', 'ChronosWithRegressor[bolt_small]', 'TemporalFusionTransformer', 'DeepAR']
Training timeseries model SeasonalNaive. Training for up to 54.5s of the 600.0s of remaining time.
	-2.2412       = Validation score (-MASE)
	0.01    s     = Training runtime
	0.01    s     = Validation (prediction) runtime
Training timeseries model RecursiveTabular. Training for up to 60.0s of the 600.0s of remaining time.
	-2.6544       = Validation score (-MASE)
	0.30    s     = Training runtime
	0.04    s     = Validation (prediction) runtime
Training timeseries model DirectTabular. Training for up to 66.6s of the 599.6s of remaining time.
	-3.4733       = Validation score (-MASE)
	0.32    s     = Training runtime
	0.04    s     = Validation (prediction) runtime
Training timeseries model DynamicOptimizedTheta. Training for up to 74.9s of the 599.2s of remaining time.
	-2.4608       = Validation score (-MASE)
	0.01    s     = Training runtime
	0.03    s     = Validation (prediction) runtime
Training timeseries model Chronos2. Training for up to 85.6s of the 599.2s of remaining time.
	-3.3834       = Validation score (-MASE)
	1.26    s     = Training runtime
	0.15    s     = Validation (prediction) runtime
Training timeseries model Chronos2SmallFineTuned. Training for up to 99.6s of the 597.8s of remaining time.
	-5.2300       = Validation score (-MASE)
	92.22   s     = Training runtime
	0.03    s     = Validation (prediction) runtime
Training timeseries model AutoETS. Training for up to 101.1s of the 505.5s of remaining time.
	-2.0280       = Validation score (-MASE)
	0.01    s     = Training runtime
	0.03    s     = Validation (prediction) runtime
Training timeseries model ChronosWithRegressor[bolt_small]. Training for up to 126.4s of the 505.4s of remaining time.
	-2.7304       = Validation score (-MASE)
	0.53    s     = Training runtime
	1.35    s     = Validation (prediction) runtime
Training timeseries model TemporalFusionTransformer. Training for up to 167.9s of the 503.6s of remaining time.
	-1.7667       = Validation score (-MASE)
	52.49   s     = Training runtime
	0.03    s     = Validation (prediction) runtime
Training timeseries model DeepAR. Training for up to 225.5s of the 451.0s of remaining time.
	-2.3421       = Validation score (-MASE)
	15.85   s     = Training runtime
	0.03    s     = Validation (prediction) runtime
Fitting 1 ensemble(s), in 1 layers.
Training ensemble model WeightedEnsemble. Training for up to 435.0s.
	Ensemble weights: {'AutoETS': 0.22, 'Chronos2SmallFineTuned': 0.06, 'DeepAR': 0.34, 'DynamicOptimizedTheta': 0.02, 'TemporalFusionTransformer': 0.36}
	-1.6408       = Validation score (-MASE)
	0.19    s     = Training runtime
	0.14    s     = Validation (prediction) runtime
Training complete. Models trained: ['SeasonalNaive', 'RecursiveTabular', 'DirectTabular', 'DynamicOptimizedTheta', 'Chronos2', 'Chronos2SmallFineTuned', 'AutoETS', 'ChronosWithRegressor[bolt_small]', 'TemporalFusionTransformer', 'DeepAR', 'WeightedEnsemble']
Total runtime: 165.53 s
Best model: WeightedEnsemble
Best model score: -1.6408

In [37]:
predictor.evaluate(ts_df)

Model not specified in predict, will default to the model with the best validation score: WeightedEnsemble

{'MASE': -1.6530247746985405}

In [38]:
pd.set_option("display.float_format", lambda x: f"{x:,.0f}")  # จัดรูปแบบตัวเลข
# 1. เตรียมข้อมูลพารามิเตอร์รอบข้างล่วงหน้า (Future Covariates)
future_data = []
for item_id in ts_df.item_ids:
    last_date = ts_df.loc[item_id].index.max()
    future_dates = pd.date_range(start=last_date, periods=3, freq="2YS")[1:]
    region = item_id.split("_")[0]
    for date in future_dates:
        # ยอดนักท่องเที่ยวระดับประเทศช่วงปี 60-62 อยู่ที่ประมาณ 35 ล้านคน
        base = 35.0
        share = {
            "Bangkok": 0.35,
            "Southern": 0.25,
            "Central": 0.15,
            "Northern": 0.15,
            "Northeastern": 0.10,
        }
        # คำนวณยอดของแต่ละภูมิภาค + สุ่ม Noise
        tourists_million = (base * share.get(region, 0.1)) + np.random.uniform(
            -0.5, 0.5
        )
        future_tourists = int(max(0.1, tourists_million) * 1000000)
        future_data.append(
            {"item_id": item_id, "timestamp": date, "tourists_mn": future_tourists}
        )
# 2. แปลงเป็น TimeSeriesDataFrame
future_covariates = TimeSeriesDataFrame.from_data_frame(
    pd.DataFrame(future_data),
    id_column="item_id",
    timestamp_column="timestamp",
)
# 3. สั่งทำนาย โดยใส่ future_covariates เข้าไปด้วย
predictions = predictor.predict(ts_df, known_covariates=future_covariates).reset_index()
predictions

Model not specified in predict, will default to the model with the best validation score: WeightedEnsemble

,item_id,timestamp,mean,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9
0,Bangkok_1,2017-01-01,"2,433,626,390","933,196,028","1,433,868,198","1,771,149,225","2,126,718,910","2,433,626,390","2,901,389,851","3,053,939,007","3,564,777,458","3,900,547,065"
1,Bangkok_1,2019-01-01,"2,480,864,037","952,021,408","1,504,631,706","1,894,371,225","2,249,787,358","2,480,864,037","2,936,559,822","3,133,913,974","3,726,096,516","4,022,056,743"
2,Bangkok_2,2017-01-01,"11,623,507,305","894,561,929","4,203,062,859","6,389,401,374","8,809,016,789","11,623,507,305","14,955,258,578","16,472,090,528","19,439,551,806","22,887,448,598"
3,Bangkok_2,2019-01-01,"12,162,887,152","-2,901,320,030","2,018,358,375","5,332,555,324","8,725,098,282","12,162,887,152","16,148,220,679","18,592,281,203","22,899,475,855","27,827,836,805"
4,Bangkok_3,2017-01-01,"46,609,471,585","28,851,800,840","36,321,052,634","40,310,270,182","44,342,082,587","46,609,471,585","50,437,359,069","53,498,582,263","59,707,486,553","66,160,109,513"
5,Bangkok_3,2019-01-01,"47,199,306,984","29,861,475,731","37,178,080,871","41,053,877,054","44,719,320,210","47,199,306,984","51,256,928,158","54,046,633,906","59,384,908,224","66,422,207,120"
6,Central_1,2017-01-01,"7,296,768,849","467,686,535","2,819,016,099","4,419,536,304","6,100,293,562","7,296,768,849","9,125,967,455","10,162,308,652","12,733,820,707","14,719,798,368"
7,Central_1,2019-01-01,"7,528,855,227","-6,045,464,019","-1,796,563,755","1,109,573,769","4,068,951,797","7,528,855,227","10,925,223,692","13,210,756,546","16,478,881,993","21,076,240,228"
8,Central_2,2017-01-01,"7,669,439,068","3,711,082,041","4,612,426,075","5,268,296,406","6,230,397,173","7,669,439,068","9,140,373,728","9,436,422,561","10,299,397,702","11,557,418,202"
9,Central_2,2019-01-01,"7,720,818,705","3,416,867,241","4,633,628,635","5,659,565,520","6,578,580,345","7,720,818,705","8,930,100,688","9,256,645,492","10,214,006,238","11,514,195,527"
10,Central_3,2017-01-01,"18,230,836,973","12,607,317,554","14,501,393,236","16,389,865,526","17,987,412,832","18,230,836,973","19,911,871,847","20,918,335,148","24,050,568,030","25,693,799,604"
11,Central_3,2019-01-01,"19,006,930,283","12,301,834,103","14,698,338,759","16,628,509,571","18,510,970,891","19,006,930,283","20,883,460,424","22,037,079,553","25,447,755,266","27,367,752,758"
12,Northern_1,2017-01-01,"4,503,293,867","1,851,027,414","2,840,076,759","3,494,264,942","4,205,344,021","4,503,293,867","5,312,035,033","5,636,676,084","6,777,383,505","7,379,816,700"
13,Northern_1,2019-01-01,"4,539,163,889","1,777,870,770","2,742,258,773","3,433,367,661","4,174,073,166","4,539,163,889","5,409,660,674","5,799,020,517","7,081,780,394","7,768,795,419"
14,Northern_2,2017-01-01,"3,864,367,873","1,383,092,586","2,237,933,528","2,832,725,232","3,382,526,207","3,864,367,873","4,568,309,977","4,856,211,889","5,727,779,134","6,378,964,177"
15,Northern_2,2019-01-01,"3,967,948,151","495,043,039","1,769,846,899","2,526,219,926","3,250,326,558","3,967,948,151","4,801,220,740","5,274,016,751","6,301,090,266","7,179,222,516"
16,Northern_3,2017-01-01,"5,075,064,270","2,519,510,564","3,423,990,659","4,044,648,720","4,627,509,015","5,075,064,270","5,754,738,285","6,063,007,375","6,959,416,834","7,602,448,848"
17,Northern_3,2019-01-01,"5,002,776,642","2,068,583,290","3,357,253,555","3,820,568,151","4,338,046,113","5,002,776,642","5,824,261,455","6,175,877,996","6,869,654,961","7,733,511,449"
18,Northeastern_1,2017-01-01,"2,306,974,395","388,709,797","1,074,482,343","1,640,398,935","2,094,982,841","2,306,974,395","2,782,750,590","3,181,181,196","3,857,168,972","4,395,835,781"
19,Northeastern_1,2019-01-01,"2,397,411,464","-859,585,925","298,951,464","1,175,757,045","1,917,290,006","2,397,411,464","3,156,599,690","3,787,973,218","4,831,716,631","5,869,732,751"
20,Northeastern_2,2017-01-01,"2,538,904,162","1,280,686,815","1,755,646,979","2,038,184,838","2,301,336,957","2,538,904,162","2,873,688,275","3,022,783,669","3,468,197,586","3,791,142,506"
21,Northeastern_2,2019-01-01,"2,505,541,232","961,905,589","1,556,064,721","1,901,506,293","2,238,163,159","2,505,541,232","2,852,708,522","3,056,311,225","3,524,524,127","3,967,098,203"
22,Northeastern_3,2017-01-01,"3,218,341,249","1,196,445,745","1,731,363,986","2,114,132,990","2,579,768,628","3,218,341,249","3,910,422,805","4,090,146,487","4,570,692,098","5,256,035,121"
23,Northeastern_3,2019-01-01,"3,334,775,804","1,157,457,700","1,911,601,566","2,317,678,380","2,780,132,100","3,334,775,804","4,000,493,474","4,259,054,852","4,936,194,428","5,485,942,566"
24,Southern_1,2017-01-01,"14,657,206,061","2,767,855,824","5,800,578,694","7,765,399,181","10,526,211,907","14,657,206,061","19,085,491,863","19,942,930,504","22,912,688,077","26,936,184,645"
25,Southern_1,2019-01-01,"15,359,992,096","2,581,498,389","6,247,367,697","8,355,749,957","11,294,534,007","15,359,992,096","19,893,491,216","20,921,586,142","24,397,106,373","28,773,492,026"
26,Southern_2,2017-01-01,"13,909,981,424","5,538,418,725","8,380,344,259","10,207,177,010","12,187,922,923","13,909,981,424","16,372,954,460","17,623,435,588","20,225,960,413","22,402,692,671"
27,Southern_2,2019-01-01,"14,247,833,945","3,821,329,389","7,329,229,352","9,586,801,601","11,783,628,503","14,247,833,945","17,175,276,686","18,542,999,630","21,127,210,071","24,181,627,466"
28,Southern_3,2017-01-01,"28,413,070,536","4,286,827,306","9,403,807,549","13,957,526,713","18,279,880,458","28,413,070,536","35,705,724,086","38,210,231,068","39,617,221,851","49,940,036,860"
29,Southern_3,2019-01-01,"29,511,505,989","-1,062,600,212","6,716,997,208","12,854,731,333","18,518,399,487","29,511,505,989","37,866,202,434","41,690,207,613","44,544,801,024","56,891,258,303"

In [39]:
predictions["year_th"] = predictions["timestamp"].dt.year + 543
predictions[["region", "size_rank"]] = predictions["item_id"].str.rsplit(
    "_", n=1, expand=True
)
predictions["size_rank"] = predictions["size_rank"].astype(int)
future_df = pd.DataFrame(future_data)
predictions = pd.merge(predictions, future_df, on=["item_id", "timestamp"], how="left")

In [40]:
actual = df[["item_id", "year", "value", "region", "size_rank", "tourists_mn"]].copy()
actual["year_th"] = actual["year"]
actual["type"] = "actual"

In [41]:
pred_export = predictions[
    ["item_id", "year_th", "region", "size_rank", "mean", "0.1", "0.9", "tourists_mn"]
].copy()
pred_export.columns = [
    "item_id",
    "year_th",
    "region",
    "size_rank",
    "value",
    "lower",
    "upper",
    "tourists_mn",
]
pred_export["type"] = "forecast"

actual_export = actual[
    ["item_id", "year_th", "region", "size_rank", "value", "tourists_mn"]
].copy()
actual_export["lower"] = None
actual_export["upper"] = None
actual_export["type"] = "actual"

combined = pd.concat([actual_export, pred_export], ignore_index=True)
combined.to_csv("../data/predict/predictions.csv", index=False)
print("Saved predictions.csv")

Saved predictions.csv

C:\Users\UNS_CT\AppData\Local\Temp\ipykernel_14952\3417174443.py:23: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([actual_export, pred_export], ignore_index=True)